server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/danteuba244/tp-microservicios-ai.git
          default-label: main
          search-paths: config
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
